version: '3.8'
services:
  web:
    image: statline:latest
    ports:
    - "8080:8080"
    environment:
        GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_auth
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    secrets:
        - source: gcp_auth

secrets:
    gcp_auth:
        external: true
